#include "std_msgs_header.idl"

module sensor_msgs {
  module msg {
    module dds_ {
      struct LaserScan_ {
        std_msgs::msg::dds_::Header_ header;
        float angle_min;
        float angle_max;
        float angle_increment;
        float time_increment;
        float scan_time;
        float range_min;
        float range_max;
        sequence<float> ranges;
        sequence<float> intensities;
      };
    };
  };
};
